"use client";
// Sprint 3 Checkpoint 15I — Shared expanded-state tab host.
//
// All five concepts reuse this tab shell so:
//   • the contextual-tab rule (only tabs available on this fixture render)
//     is enforced in one place;
//   • tab-switch clicks don't bubble up to the card's outer click handler
//     (each concept marks its outer clickable surface with data-card-open;
//     tabs use stopPropagation);
//   • the tab body scrolls independently rather than jerking the page.
//
// Concepts choose whether/how to render a header above the tabs.

import { useState, useCallback, type ReactNode, type MouseEvent } from "react";
import type { WorkIntakeFixture } from "../fixtures";
import { formatBytes, formatCurrency } from "../fixtures";

export type TabKey = "conversation" | "attachments" | "invoice" | "activity";

const TAB_LABEL: Record<TabKey, string> = {
  conversation: "Conversation",
  attachments: "Attachments",
  invoice: "Invoice Review",
  activity: "Activity",
};

interface Props {
  fixture: WorkIntakeFixture;
  defaultTab?: TabKey;
}

export default function TabHost({ fixture, defaultTab }: Props) {
  const initial: TabKey =
    defaultTab && fixture.availableTabs.includes(defaultTab)
      ? defaultTab
      : (fixture.availableTabs[0] ?? "activity");
  const [active, setActive] = useState<TabKey>(initial);

  // Prevent tab clicks from re-triggering the card's outer open handler.
  const onTabClick = useCallback((e: MouseEvent, k: TabKey) => {
    e.stopPropagation();
    setActive(k);
  }, []);

  const stopBubble = useCallback((e: MouseEvent) => e.stopPropagation(), []);

  return (
    <div className="th" onClick={stopBubble} role="presentation">
      <div className="th__tabs" role="tablist">
        {fixture.availableTabs.map((k) => (
          <button
            type="button"
            key={k}
            role="tab"
            aria-selected={active === k}
            className={`th__tab ${active === k ? "th__tab--active" : ""}`}
            onClick={(e) => onTabClick(e, k)}
            data-testid={`tab-${k}`}
          >
            {TAB_LABEL[k]}
          </button>
        ))}
      </div>
      <div className="th__body" role="tabpanel" data-testid={`tabpanel-${active}`}>
        {active === "conversation" && renderConversation(fixture)}
        {active === "attachments" && renderAttachments(fixture)}
        {active === "invoice" && renderInvoice(fixture)}
        {active === "activity" && renderActivity(fixture)}
      </div>
      <ThCss />
    </div>
  );
}

function renderConversation(fixture: WorkIntakeFixture): ReactNode {
  if (!fixture.conversation) {
    return (
      <p className="th__muted">
        This item was generated by Spectre or by another system — there is no email
        conversation associated with it.
      </p>
    );
  }
  const c = fixture.conversation;
  return (
    <article className="th__conv">
      <header className="th__conv-head">
        <div>
          <p className="th__conv-from">{c.from}</p>
          <p className="th__conv-addr">{c.fromAddress}</p>
        </div>
        <p className="th__conv-when">
          {new Date(c.receivedAtISO).toLocaleString("en-CA", {
            month: "short",
            day: "numeric",
            hour: "numeric",
            minute: "2-digit",
          })}
        </p>
      </header>
      <p className="th__conv-subject">{c.subject}</p>
      <p className="th__conv-preview">{c.preview}</p>
      {c.messageCount > 1 ? (
        <p className="th__muted">Conversation contains {c.messageCount} messages.</p>
      ) : null}
      <div className="th__actions">
        <button type="button" className="th__btn">Reply</button>
        <button type="button" className="th__btn th__btn--ghost">View full thread</button>
      </div>
    </article>
  );
}

function renderAttachments(fixture: WorkIntakeFixture): ReactNode {
  if (fixture.attachments.length === 0) {
    return <p className="th__muted">No attachments on this item.</p>;
  }
  return (
    <ul className="th__attach" role="list">
      {fixture.attachments.map((a) => (
        <li key={a.filename} className="th__attach-row">
          <div className="th__attach-main">
            <p className="th__attach-name">{a.filename}</p>
            <p className="th__attach-meta">
              {a.contentType} · {formatBytes(a.byteLength)} · {a.classification.toLowerCase()}
              {a.isInline ? " · inline" : ""}
              {" · extraction "}
              <span className={`th__pill th__pill--${a.extractionState.toLowerCase()}`}>
                {a.extractionState.toLowerCase()}
              </span>
              {" · analysis "}
              <span className={`th__pill th__pill--${a.analysisState.toLowerCase()}`}>
                {a.analysisState.toLowerCase()}
              </span>
            </p>
          </div>
          <div className="th__attach-actions">
            <button type="button" className="th__btn">View PDF</button>
            <button type="button" className="th__btn th__btn--ghost">Download</button>
          </div>
        </li>
      ))}
    </ul>
  );
}

function renderInvoice(fixture: WorkIntakeFixture): ReactNode {
  if (!fixture.invoice) {
    return (
      <p className="th__muted">
        No invoice extraction on this item. (This tab should not render for this
        fixture — see availableTabs.)
      </p>
    );
  }
  const inv = fixture.invoice;
  return (
    <div className="th__inv">
      <dl className="th__inv-facts">
        <div>
          <dt>Extracted vendor (from PDF)</dt>
          <dd>{inv.vendorGuess ?? "—"}</dd>
        </div>
        <div>
          <dt>Vendor match</dt>
          <dd>
            {inv.vendorMatchedToSpectreRecord
              ? "Matched to Spectre vendor record"
              : "Not matched — reviewer must select or create a vendor"}
          </dd>
        </div>
        <div>
          <dt>Invoice number</dt>
          <dd>{inv.invoiceNumber ?? "—"}</dd>
        </div>
        <div>
          <dt>Total</dt>
          <dd>{inv.total && inv.currency ? formatCurrency(inv.total, inv.currency) : "—"}</dd>
        </div>
        <div>
          <dt>Capital vs. operating</dt>
          <dd>{inv.capitalOrOperating.replace(/_/g, " ")}</dd>
        </div>
      </dl>
      {inv.findings.length > 0 ? (
        <div className="th__findings">
          <p className="th__findings-h">Analyser findings</p>
          <ul>
            {inv.findings.map((f) => (
              <li key={f.key}>
                <span className={`th__pill th__pill--sev-${f.severity.toLowerCase()}`}>
                  {f.severity.toLowerCase()}
                </span>
                <span>{f.statement}</span>
              </li>
            ))}
          </ul>
        </div>
      ) : null}
      <div className="th__actions">
        <button type="button" className="th__btn">Match vendor</button>
        <button type="button" className="th__btn th__btn--ghost">Create new vendor</button>
      </div>
    </div>
  );
}

function renderActivity(fixture: WorkIntakeFixture): ReactNode {
  return (
    <ol className="th__act" role="list">
      {fixture.activity.map((a, i) => (
        <li key={i} className="th__act-row">
          <span className="th__act-when">{a.at}</span>
          <span className="th__act-actor">{a.actor}</span>
          <span className="th__act-action">{a.action}</span>
          {a.note ? <span className="th__act-note">— {a.note}</span> : null}
        </li>
      ))}
    </ol>
  );
}

function ThCss() {
  return (
    <style dangerouslySetInnerHTML={{ __html: `
      .th { border-top: 1px solid #ede6d3; margin-top: 8px; padding-top: 8px; }
      .th__tabs { display: flex; gap: 2px; border-bottom: 1px solid #ede6d3; margin-bottom: 8px; }
      .th__tab { background: transparent; border: 0; border-bottom: 2px solid transparent; padding: 6px 12px; font-size: 12px; cursor: pointer; color: #635a4a; }
      .th__tab:hover { color: #2b2b2b; }
      .th__tab--active { border-bottom-color: #2f4739; color: #2b2b2b; font-weight: 600; }
      .th__body { min-height: 100px; padding: 4px 2px 8px; font-size: 13px; }
      .th__muted { color: #8a7f6a; font-style: italic; margin: 6px 0; }

      .th__conv-head { display: flex; justify-content: space-between; gap: 12px; align-items: flex-start; margin-bottom: 6px; }
      .th__conv-from { margin: 0; font-weight: 600; font-size: 13px; }
      .th__conv-addr { margin: 0; font-size: 11px; color: #8a7f6a; }
      .th__conv-when { margin: 0; font-size: 11px; color: #8a7f6a; }
      .th__conv-subject { margin: 8px 0 4px; font-weight: 600; font-size: 13px; }
      .th__conv-preview { margin: 0; color: #555; line-height: 1.45; }

      .th__actions { display: flex; gap: 6px; margin-top: 10px; }
      .th__btn { border: 1px solid #2f4739; background: #2f4739; color: #fdfaf1; padding: 5px 12px; border-radius: 4px; font-size: 12px; cursor: pointer; }
      .th__btn:hover { background: #24382c; }
      .th__btn--ghost { background: transparent; color: #2f4739; }
      .th__btn--ghost:hover { background: rgba(47, 71, 57, 0.06); }

      .th__attach { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 6px; }
      .th__attach-row { display: flex; justify-content: space-between; align-items: flex-start; gap: 12px; padding: 8px 10px; border: 1px solid #ede6d3; border-radius: 4px; background: #fbf7ee; }
      .th__attach-name { margin: 0; font-weight: 600; font-size: 13px; }
      .th__attach-meta { margin: 3px 0 0; font-size: 11px; color: #635a4a; }
      .th__attach-actions { display: flex; gap: 4px; }

      .th__inv-facts { display: grid; grid-template-columns: max-content 1fr; row-gap: 6px; column-gap: 12px; margin: 0 0 10px; }
      .th__inv-facts > div { display: contents; }
      .th__inv-facts dt { font-size: 11px; color: #8a7f6a; letter-spacing: 0.3px; }
      .th__inv-facts dd { margin: 0; font-size: 13px; }
      .th__findings { margin: 8px 0; }
      .th__findings-h { margin: 0 0 4px; font-size: 11px; letter-spacing: 1px; text-transform: uppercase; color: #8a7f6a; font-weight: 600; }
      .th__findings ul { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 4px; }
      .th__findings li { display: flex; gap: 8px; font-size: 12px; align-items: flex-start; }

      .th__pill { display: inline-block; font-size: 10px; padding: 1px 6px; border-radius: 2px; text-transform: uppercase; letter-spacing: 0.5px; }
      .th__pill--complete, .th__pill--sev-info { background: #e6e2d8; color: #635a4a; }
      .th__pill--partial, .th__pill--pending { background: #f4ecc9; color: #7a601f; }
      .th__pill--unreadable, .th__pill--skipped, .th__pill--sev-high { background: #f3d8cf; color: #8a4227; }
      .th__pill--sev-medium { background: #f4ecc9; color: #7a601f; }
      .th__pill--sev-low { background: #e6e2d8; color: #635a4a; }

      .th__act { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 4px; font-size: 12px; }
      .th__act-row { display: flex; gap: 6px; padding: 4px 0; border-bottom: 1px dashed #ede6d3; }
      .th__act-row:last-child { border-bottom: 0; }
      .th__act-when { color: #8a7f6a; min-width: 80px; font-variant-numeric: tabular-nums; }
      .th__act-actor { font-weight: 600; min-width: 90px; }
      .th__act-action { min-width: 140px; color: #2f4739; }
      .th__act-note { color: #635a4a; }
    ` }} />
  );
}
