// Executive Summary — cover-page At-a-Glance KPIs + reactive
// headline narrative.
//
// This service replaces the seven hardcoded React literals that
// previously lived in monthly-package.ts (six KPI cards + the
// headline). Per the Jonas-readiness audit
// (docs/monthly-reporting-data-lineage-audit.md §3 Tier 1, item 1)
// these were the HIGHEST-RISK item in the package — the first
// numbers a board member sees on the cover, which after a Jonas
// import would have continued to read `$14.62M YTD Revenue`,
// `$3.18M NOI`, etc., regardless of real GL data.
//
// Now:
//   • Every KPI value flows from a typed `ExecutiveSummaryInput`.
//   • The headline narrative is generated by `buildExecutiveSummaryHeadline()`
//     — branches on operating, capital, balance-sheet, and AR signals
//     to produce favorable / monitor / unfavorable copy.
//   • Each input carries a `MonthlyAccountingDataSource` tag; the
//     rollup is `dataSource: "live" | "demo"` matching the existing
//     package convention.
//
// The shape of `ExecutiveSummaryOutput` mirrors the existing
// `pkg.executiveSummary` block exactly — same `KpiCard[]`, same
// `headline: string`, same `consideration: BoardConsideration`.
// React on page.tsx renders the result unchanged.

import type { ReportingPeriod } from "@/lib/reporting/reporting-period";
import type {
  BalanceSheetSnapshot,
  IncomeStatementSnapshot,
} from "@/lib/reporting/ledger/contracts";
import type { ReportingLedger } from "@/lib/reporting/ledger/read-api";
import type { ReportingLedgerWriter } from "@/lib/reporting/ledger/write-api";
import { BalanceSheetProjection } from "@/lib/reporting/ledger/projections/balance-sheet-projection";
import { IncomeStatementProjection } from "@/lib/reporting/ledger/projections/income-statement-projection";
import {
  type MonthlyAccountingDataSource,
  formatMoneyShort,
  formatVariancePct,
  toLegacyDataSource,
} from "@/lib/reporting/monthly-accounting-contract";
import type {
  KpiCard,
  KpiTone,
  BoardConsideration,
  ReportingDataSource,
} from "@/lib/reporting/monthly-package";

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

/**
 * A single accounting-backed metric with its budget comparator and
 * provenance tag. Future Phase 1 wiring populates these from
 * `getGLAccountTotals()` / `getBalanceSheet()` reads against
 * Jonas-imported journals.
 *
 * `comparator` may be `null` to signal "budget / policy comparator
 * not yet available" (a real condition during partial Jonas
 * imports — actuals may post before the budget snapshot lands). The
 * builder renders an appropriate fallback in the KPI card and the
 * commentary generator omits the corresponding clause.
 */
type AccountingMetricInput = {
  /** Actual YTD value in dollars (or ratio for reserveCoverage; or
   *  fraction 0..1 for AR / F&B percentages). */
  actual: number;
  /** Budget or policy comparator (same units as `actual`). `null`
   *  marks the comparator as not-yet-available. */
  comparator: number | null;
  dataSource: MonthlyAccountingDataSource;
};

/**
 * Optional headline-narrative side-input. The static narrative cited
 * an F&B subsidy line; when the data exists the headline includes
 * that sentence, when it doesn't the headline omits it gracefully.
 */
export type FbSubsidyInput = {
  /** Current F&B subsidy as a fraction of operating dues (0..1). */
  actual: number;
  /** Policy ceiling — typically 0.08. */
  ceiling: number;
  /** Direction of the trailing-12-month trend. */
  trend: "improving" | "stable" | "worsening";
  dataSource: MonthlyAccountingDataSource;
};

/**
 * The typed input to the Executive Summary builder. Phase 1 wiring
 * services produce this shape from prisma reads; the demo input
 * factory (`buildDemoExecutiveSummaryInput`) produces a seeded
 * version for the current package build.
 */
export type ExecutiveSummaryInput = {
  period: ReportingPeriod;
  clubName: string;
  /** Total operating revenue YTD (dollars). */
  ytdRevenue: AccountingMetricInput;
  /** NOI before depreciation YTD (dollars). */
  ytdNoiBeforeDepreciation: AccountingMetricInput;
  /** Capital income YTD (dollars; initiation fees + capital dues +
   *  investment income + transfer-from-ops). */
  ytdCapitalIncome: AccountingMetricInput;
  /** Reserve coverage ratio — reserve balance ÷ 3-year average
   *  capital spend. `actual` is the ratio (e.g. 1.42); `comparator`
   *  is the policy floor (e.g. 1.25). */
  reserveCoverage: AccountingMetricInput;
  /** Working capital — current assets − current liabilities. */
  workingCapital: AccountingMetricInput;
  /** AR aging: `actual` is the current-bucket share (0..1);
   *  `comparator` is the over-90-day share (0..1) — semantically a
   *  watch indicator, not a target. Tone derives from the
   *  watchThreshold below. */
  arAging: AccountingMetricInput & {
    /** Over-90 fraction that triggers amber (typically 0.05). */
    watchThreshold: number;
  };
  /** Optional F&B subsidy line for the headline narrative. */
  fbSubsidy: FbSubsidyInput | null;
};

// ---------------------------------------------------------------------------
// Outputs
// ---------------------------------------------------------------------------

/**
 * Output shape — exactly matches the existing `executiveSummary`
 * block on `MonthlyReportingPackage` so React doesn't need any
 * changes. Six KPI cards in fixed order + headline + consideration.
 */
export type ExecutiveSummaryOutput = {
  dataSource: ReportingDataSource;
  kpis: KpiCard[];
  headline: string;
  consideration: BoardConsideration;
};

// ---------------------------------------------------------------------------
// Tone classification per KPI
// ---------------------------------------------------------------------------

/** Standard variance bands for revenue / NOI / capital income.
 *  Inside ±1 % → neutral; favourable up to budget → green; below
 *  budget by 0–5 % → amber; below by ≥ 5 % → red. A `null` or `0`
 *  comparator → neutral (we can't classify against a missing
 *  budget; the headline will note it). */
function toneForBudgetMetric(actual: number, budget: number | null): KpiTone {
  if (budget === null || budget <= 0) return "neutral";
  const variancePct = (actual - budget) / Math.abs(budget);
  if (variancePct >= -0.01) return "green";
  if (variancePct >= -0.05) return "amber";
  return "red";
}

/** Reserve coverage tone — comparator is the policy floor (e.g.
 *  1.25). Above floor → green; within 5 % of floor → amber; below →
 *  red. `null` floor → neutral. */
function toneForReserveCoverage(ratio: number, floor: number | null): KpiTone {
  if (floor === null || floor <= 0) return "neutral";
  if (ratio >= floor) return "green";
  if (ratio >= floor * 0.95) return "amber";
  return "red";
}

/** Working capital tone — same band logic as reserve coverage. */
function toneForWorkingCapital(amount: number, floor: number | null): KpiTone {
  if (floor === null || floor <= 0) return "neutral";
  if (amount >= floor) return "green";
  if (amount >= floor * 0.95) return "amber";
  return "red";
}

/** AR aging tone — drives off the over-90 share crossing the watch
 *  threshold. Below threshold → green; up to 1.5 × threshold →
 *  amber; above 1.5 × threshold → red. */
function toneForArAging(over90Pct: number, watchThreshold: number): KpiTone {
  if (over90Pct < watchThreshold) return "green";
  if (over90Pct < watchThreshold * 1.5) return "amber";
  return "red";
}

// ---------------------------------------------------------------------------
// Pre-format helpers
// ---------------------------------------------------------------------------

function formatPct(fraction: number): string {
  return `${(fraction * 100).toFixed(1)}%`;
}

function formatRatio(ratio: number): string {
  return `${ratio.toFixed(2)}x`;
}

function formatRatioDelta(actual: number, floor: number): string {
  const delta = actual - floor;
  const abs = Math.abs(delta).toFixed(2);
  if (delta > 0) return `${abs}x above floor`;
  if (delta < 0) return `${abs}x below floor`;
  return "at floor";
}

function formatDollarCushion(amount: number, floor: number): string {
  const delta = amount - floor;
  if (delta > 0) return `${formatMoneyShort(delta)} cushion`;
  if (delta < 0) return `${formatMoneyShort(Math.abs(delta))} short of floor`;
  return "at floor";
}

// ---------------------------------------------------------------------------
// KPI card builders (one per cover tile)
// ---------------------------------------------------------------------------

/** Pre-built "comparator pending" comparison row. Used when a KPI's
 *  budget / policy comparator is null (budget not yet posted for
 *  the period). The KPI tile renders `value: "Pending"` with a
 *  conservative "comparative not available" variance string so the
 *  board sees that the comparison is in-flight rather than zero. */
const PENDING_COMPARATOR_ROW = {
  label: "vs Budget",
  value: "Pending",
  variance: "comparative not available",
} as const;

function buildYtdRevenueCard(input: AccountingMetricInput): KpiCard {
  if (input.comparator === null) {
    return {
      key: "ytd-revenue",
      label: "YTD Revenue",
      value: formatMoneyShort(input.actual),
      context: "Total operating revenue earned through the period close.",
      comparison: { ...PENDING_COMPARATOR_ROW },
      tone: "neutral",
    };
  }
  const variancePct = (input.actual - input.comparator) / Math.abs(input.comparator);
  const sign = variancePct >= 0 ? "above" : "below";
  return {
    key: "ytd-revenue",
    label: "YTD Revenue",
    value: formatMoneyShort(input.actual),
    context: "Total operating revenue earned through the period close.",
    comparison: {
      label: "vs Budget",
      value: formatMoneyShort(input.comparator),
      variance: `${formatVariancePct(variancePct)} ${sign} plan`,
    },
    tone: toneForBudgetMetric(input.actual, input.comparator),
  };
}

function buildNoiCard(input: AccountingMetricInput): KpiCard {
  if (input.comparator === null) {
    return {
      key: "noi",
      label: "NOI Before Depreciation",
      value: formatMoneyShort(input.actual),
      context: "Operating margin before non-cash depreciation expense.",
      comparison: { ...PENDING_COMPARATOR_ROW },
      tone: "neutral",
    };
  }
  const variancePct = (input.actual - input.comparator) / Math.abs(input.comparator);
  const sign = variancePct >= 0 ? "above" : "below";
  return {
    key: "noi",
    label: "NOI Before Depreciation",
    value: formatMoneyShort(input.actual),
    context: "Operating margin before non-cash depreciation expense.",
    comparison: {
      label: "vs Budget",
      value: formatMoneyShort(input.comparator),
      variance: `${formatVariancePct(variancePct)} ${sign} plan`,
    },
    tone: toneForBudgetMetric(input.actual, input.comparator),
  };
}

function buildCapitalIncomeCard(input: AccountingMetricInput): KpiCard {
  if (input.comparator === null) {
    return {
      key: "capital-income",
      label: "Capital Income",
      value: formatMoneyShort(input.actual),
      context: "Initiation fees, capital dues, and transfer fees collected.",
      comparison: { ...PENDING_COMPARATOR_ROW },
      tone: "neutral",
    };
  }
  const variancePct = (input.actual - input.comparator) / Math.abs(input.comparator);
  const sign = variancePct >= 0 ? "above" : "below";
  return {
    key: "capital-income",
    label: "Capital Income",
    value: formatMoneyShort(input.actual),
    context: "Initiation fees, capital dues, and transfer fees collected.",
    comparison: {
      label: "vs Budget",
      value: formatMoneyShort(input.comparator),
      variance: `${formatVariancePct(variancePct)} ${sign} plan`,
    },
    tone: toneForBudgetMetric(input.actual, input.comparator),
  };
}

function buildReserveCoverageCard(input: AccountingMetricInput): KpiCard {
  if (input.comparator === null) {
    return {
      key: "reserve-coverage",
      label: "Reserve Coverage",
      value: formatRatio(input.actual),
      context: "Reserve balance relative to three-year average capital spend.",
      comparison: {
        label: "Policy target",
        value: "Pending",
        variance: "policy target not configured",
      },
      tone: "neutral",
    };
  }
  return {
    key: "reserve-coverage",
    label: "Reserve Coverage",
    value: formatRatio(input.actual),
    context: "Reserve balance relative to three-year average capital spend.",
    comparison: {
      label: "Policy target",
      value: formatRatio(input.comparator),
      variance: formatRatioDelta(input.actual, input.comparator),
    },
    tone: toneForReserveCoverage(input.actual, input.comparator),
  };
}

function buildWorkingCapitalCard(input: AccountingMetricInput): KpiCard {
  if (input.comparator === null) {
    return {
      key: "working-capital",
      label: "Working Capital",
      value: formatMoneyShort(input.actual),
      context: "Current assets less current liabilities at period end.",
      comparison: {
        label: "Policy floor",
        value: "Pending",
        variance: "policy floor not configured",
      },
      tone: "neutral",
    };
  }
  return {
    key: "working-capital",
    label: "Working Capital",
    value: formatMoneyShort(input.actual),
    context: "Current assets less current liabilities at period end.",
    comparison: {
      label: "Policy floor",
      value: formatMoneyShort(input.comparator),
      variance: formatDollarCushion(input.actual, input.comparator),
    },
    tone: toneForWorkingCapital(input.actual, input.comparator),
  };
}

function buildArCard(
  input: AccountingMetricInput & { watchThreshold: number },
): KpiCard {
  if (input.comparator === null) {
    return {
      key: "ar-current",
      label: "AR Current %",
      value: formatPct(input.actual),
      context: "Share of member receivables aged 30 days or less.",
      comparison: {
        label: "Over-90 days",
        value: "Pending",
        variance: `Watch threshold ${formatPct(input.watchThreshold)}`,
      },
      tone: "neutral",
    };
  }
  // `actual` is current% (0..1); `comparator` is over-90% (0..1).
  return {
    key: "ar-current",
    label: "AR Current %",
    value: formatPct(input.actual),
    context: "Share of member receivables aged 30 days or less.",
    comparison: {
      label: "Over-90 days",
      value: formatPct(input.comparator),
      variance: `Watch threshold ${formatPct(input.watchThreshold)}`,
    },
    tone: toneForArAging(input.comparator, input.watchThreshold),
  };
}

// ---------------------------------------------------------------------------
// Consideration cascade — worst KPI tone wins
// ---------------------------------------------------------------------------

function cascadeConsideration(kpis: KpiCard[]): BoardConsideration {
  const tones = new Set(kpis.map((k) => k.tone ?? "neutral"));
  if (tones.has("red")) return "committee-review";
  if (tones.has("amber")) return "monitor";
  return "no-action";
}

// ---------------------------------------------------------------------------
// Reactive headline narrative — branches on each KPI's tone
// ---------------------------------------------------------------------------

/**
 * Reactive cover-page narrative generator.
 *
 * Composition (when full data is available, in order):
 *   1. Opening verdict — "in line with / above / below plan" based on
 *      worst KPI tone. Conservative language; no all-caps drama.
 *   2. Revenue clause — actual + variance vs budget in $ and %.
 *   3. NOI clause — same.
 *   4. Capital Income clause — same.
 *   5. Reserve Coverage clause — names the policy floor relationship.
 *   6. Largest-variance callout — names the single most favourable and
 *      (if separately material) the single most unfavourable variance.
 *   7. Pillar verdict + action line.
 *
 * Fallback branches:
 *   - All three primary comparators (revenue / NOI / capital) are
 *     `null` → emit a short fallback paragraph; do not invent
 *     verdicts.
 *   - One or two are `null` → omit those clauses and add a
 *     "comparators pending for: ..." aside so the reader sees the
 *     omission was intentional.
 *
 * Language rules (board-report tone, restrained):
 *   - Numeric variances are stated, not editorialised. "+3.7 % above
 *     plan" not "tracking favorably to plan".
 *   - "Off plan" never appears in all caps.
 *   - The word "materially" only applies when |variance| ≥ 10 %.
 *   - The opener avoids "OFF PLAN" / "FAVORABLE" / "STRONG" — uses
 *     "operating in line with plan" / "operating below plan" /
 *     "operating above plan".
 */
export function buildExecutiveSummaryHeadline(
  input: ExecutiveSummaryInput,
  kpis: KpiCard[],
): string {
  const period = input.period.periodLabel;

  // Gather variances for the three primary metrics so the headline
  // can name them individually + identify the largest favourable
  // and largest unfavourable.
  type PrimaryVariance = {
    /** Pretty label used in the headline. */
    label: string;
    /** Variance % (actual − budget) / |budget|, or null if budget missing. */
    variancePct: number | null;
    /** Variance amount in dollars, or null if budget missing. */
    varianceAmount: number | null;
    actual: number;
    comparator: number | null;
  };
  const primaries: PrimaryVariance[] = [
    {
      label: "operating revenue",
      ...computeVariance(input.ytdRevenue),
    },
    {
      label: "NOI before depreciation",
      ...computeVariance(input.ytdNoiBeforeDepreciation),
    },
    {
      label: "capital income",
      ...computeVariance(input.ytdCapitalIncome),
    },
  ];
  const availablePrimaries = primaries.filter((p) => p.variancePct !== null);
  const missingPrimaryLabels = primaries
    .filter((p) => p.variancePct === null)
    .map((p) => p.label);

  // -----------------------------------------------------------------
  // FALLBACK BRANCH — every primary comparator is null. The headline
  // does not attempt to verdict-cast; it states that the comparators
  // are pending so the reader knows the omission is intentional.
  // -----------------------------------------------------------------
  if (availablePrimaries.length === 0) {
    return (
      `${input.clubName} — ${period} cover summary not yet available. ` +
      `Budget comparators are pending for operating revenue, NOI before depreciation, and capital income. ` +
      `YTD actuals are listed in the cards above; the narrative will populate once full data flows from the accounting service.`
    );
  }

  // -----------------------------------------------------------------
  // FULL OR PARTIAL NARRATIVE
  // -----------------------------------------------------------------

  // 1. Opening verdict — based on worst KPI tone across the cards.
  //    Conservative wording; no all-caps drama.
  const tones = new Set(kpis.map((k) => k.tone ?? "neutral"));
  const anyRed = tones.has("red");
  const anyAmber = tones.has("amber");
  let opener: string;
  if (anyRed) {
    opener = `${input.clubName} is operating below plan through ${period}.`;
  } else if (anyAmber) {
    opener = `${input.clubName} is operating largely in line with plan through ${period}, with specific items to monitor.`;
  } else {
    opener = `${input.clubName} is operating in line with plan through ${period}.`;
  }

  // 2-4. Primary-metric clauses — one sentence per available metric.
  const primaryClauses: string[] = [];
  const revClause = describePrimaryVariance({
    label: "Operating revenue",
    actual: input.ytdRevenue.actual,
    comparator: input.ytdRevenue.comparator,
  });
  if (revClause) primaryClauses.push(revClause);
  const noiClause = describePrimaryVariance({
    label: "NOI before depreciation",
    actual: input.ytdNoiBeforeDepreciation.actual,
    comparator: input.ytdNoiBeforeDepreciation.comparator,
  });
  if (noiClause) primaryClauses.push(noiClause);
  const capClause = describePrimaryVariance({
    label: "Capital income",
    actual: input.ytdCapitalIncome.actual,
    comparator: input.ytdCapitalIncome.comparator,
  });
  if (capClause) primaryClauses.push(capClause);

  // Partial-data aside — only emitted when SOME primaries were
  // omitted (1 or 2 missing). The full-fallback branch above
  // handles 3-missing.
  let partialDataAside: string | null = null;
  if (missingPrimaryLabels.length > 0) {
    partialDataAside =
      `Comparators are not yet posted for: ${missingPrimaryLabels.join(", ")} — those clauses will populate when budget data flows.`;
  }

  // 5. Reserve coverage clause.
  let reserveClause: string;
  if (input.reserveCoverage.comparator === null) {
    reserveClause = `Capital reserve coverage is ${formatRatio(input.reserveCoverage.actual)}; the policy floor is not yet configured in the reporting service.`;
  } else {
    const ratio = input.reserveCoverage.actual;
    const floor = input.reserveCoverage.comparator;
    if (ratio >= floor) {
      reserveClause = `Capital reserve coverage holds at ${formatRatio(ratio)}, above the ${formatRatio(floor)} policy floor.`;
    } else if (ratio >= floor * 0.95) {
      reserveClause = `Capital reserve coverage sits at ${formatRatio(ratio)}, at the ${formatRatio(floor)} policy floor; the margin warrants monitoring.`;
    } else {
      reserveClause = `Capital reserve coverage has declined to ${formatRatio(ratio)}, below the ${formatRatio(floor)} policy floor.`;
    }
  }

  // 6. Largest-variance callout — names the most favourable and (if
  //    separately material) the most unfavourable. Restrained:
  //    "no material variances" is an acceptable callout when none
  //    exceed the 5 % material threshold.
  const callout = buildLargestVarianceCallout(availablePrimaries);

  // 7. Optional F&B subsidy clause — only when data is available.
  let fbClause: string | null = null;
  if (input.fbSubsidy) {
    const fb = input.fbSubsidy;
    const direction =
      fb.trend === "improving"
        ? "continuing a downward trend"
        : fb.trend === "worsening"
          ? "and trending upward"
          : "and holding steady";
    if (fb.actual <= fb.ceiling) {
      fbClause = `The F&B subsidy of dues is ${formatPct(fb.actual)}, below the ${formatPct(fb.ceiling)} ceiling, ${direction}.`;
    } else {
      fbClause = `The F&B subsidy of dues is ${formatPct(fb.actual)}, above the ${formatPct(fb.ceiling)} ceiling, ${direction}.`;
    }
  }

  // 8. Pillar verdict.
  function pillarVerdict(...keys: string[]): "favorable" | "monitor" | "unfavorable" {
    const pillarTones = kpis
      .filter((k) => keys.includes(k.key))
      .map((k) => k.tone ?? "neutral");
    if (pillarTones.includes("red")) return "unfavorable";
    if (pillarTones.includes("amber")) return "monitor";
    return "favorable";
  }
  const p1 = pillarVerdict("ytd-revenue", "noi");
  const p2 = pillarVerdict("capital-income", "reserve-coverage");
  const p3 = pillarVerdict("working-capital", "ar-current");
  const pillarLine =
    [p1, p2, p3].every((v) => v === "favorable")
      ? "Pillar 1 Operating, Pillar 2 Capital, and Pillar 3 Balance Sheet Stewardship are favorable."
      : [p1, p2, p3].some((v) => v === "unfavorable")
        ? "One or more of Pillar 1 Operating, Pillar 2 Capital, or Pillar 3 Balance Sheet Stewardship is showing unfavourable signals."
        : "Pillars are mostly favorable with specific items to monitor.";

  // 9. Closing action statement.
  const actionLine = anyRed
    ? "Board attention is required this period."
    : anyAmber
      ? "No Board action is required; the items above warrant Committee monitoring."
      : "No Board action is required this period.";

  // Compose. Each clause is its own sentence — board-report cadence.
  const parts: string[] = [opener];
  parts.push(...primaryClauses);
  parts.push(reserveClause);
  if (callout) parts.push(callout);
  if (fbClause) parts.push(fbClause);
  if (partialDataAside) parts.push(partialDataAside);
  parts.push(pillarLine);
  parts.push(actionLine);
  return parts.join(" ");
}

/** Internal: compute variance + amount for a primary metric, with
 *  null-safe handling. */
function computeVariance(input: AccountingMetricInput): {
  variancePct: number | null;
  varianceAmount: number | null;
  actual: number;
  comparator: number | null;
} {
  if (input.comparator === null || input.comparator === 0) {
    return {
      variancePct: null,
      varianceAmount: null,
      actual: input.actual,
      comparator: input.comparator,
    };
  }
  return {
    variancePct: (input.actual - input.comparator) / Math.abs(input.comparator),
    varianceAmount: input.actual - input.comparator,
    actual: input.actual,
    comparator: input.comparator,
  };
}

/** Per-metric prose sentence. Uses board-report cadence: lead with
 *  the actual, follow with the comparator + variance ($ and %). Adds
 *  the word "materially" only when |variance| ≥ 10 %. Returns null
 *  when the comparator is null (skip clause). */
function describePrimaryVariance(args: {
  label: string;
  actual: number;
  comparator: number | null;
}): string | null {
  if (args.comparator === null) return null;
  const variancePct = (args.actual - args.comparator) / Math.abs(args.comparator);
  const absPct = Math.abs(variancePct);
  const varianceAmount = args.actual - args.comparator;
  if (absPct < 0.01) {
    return `${args.label} closed at ${formatMoneyShort(args.actual)}, essentially at the ${formatMoneyShort(args.comparator)} plan.`;
  }
  const direction = variancePct > 0 ? "favorable" : "unfavorable";
  const materialPrefix = absPct >= 0.10 ? "materially " : "";
  return (
    `${args.label} closed at ${formatMoneyShort(args.actual)}, ` +
    `${materialPrefix}${direction} to the ${formatMoneyShort(args.comparator)} plan ` +
    `(${formatVariancePct(variancePct)}, ${formatMoneyShort(Math.abs(varianceAmount))}).`
  );
}

/** Identify the single largest favourable and largest unfavourable
 *  variance across the available primary metrics. Emits a one-
 *  sentence callout. Returns null when nothing material to name
 *  (e.g. all primaries within ±5 % — emit a neutral "no material
 *  variances" line instead of staying silent so the reader knows
 *  the cover was reviewed for them). */
function buildLargestVarianceCallout(
  primaries: Array<{ label: string; variancePct: number | null }>,
): string | null {
  const available = primaries.filter(
    (p): p is { label: string; variancePct: number } => p.variancePct !== null,
  );
  if (available.length === 0) return null;
  // Material threshold for the callout: 5 % (matches the amber
  // band used for KPI tone classification).
  const MATERIAL_THRESHOLD = 0.05;
  const materialFavorable = available
    .filter((p) => p.variancePct >= MATERIAL_THRESHOLD)
    .sort((a, b) => b.variancePct - a.variancePct);
  const materialUnfavorable = available
    .filter((p) => p.variancePct <= -MATERIAL_THRESHOLD)
    .sort((a, b) => a.variancePct - b.variancePct);

  if (materialFavorable.length === 0 && materialUnfavorable.length === 0) {
    return "No primary metric is materially off plan (variance ≥ 5%).";
  }
  const parts: string[] = [];
  if (materialFavorable.length > 0) {
    const top = materialFavorable[0];
    parts.push(
      `The largest favourable variance is ${top.label} (${formatVariancePct(top.variancePct)}).`,
    );
  }
  if (materialUnfavorable.length > 0) {
    const top = materialUnfavorable[0];
    parts.push(
      `The largest unfavourable variance is ${top.label} (${formatVariancePct(top.variancePct)}).`,
    );
  }
  return parts.join(" ");
}

// ---------------------------------------------------------------------------
// The builder
// ---------------------------------------------------------------------------

/**
 * Build the executive summary block from typed input. Pure function;
 * deterministic given inputs. Six KPI cards + reactive headline +
 * consideration cascade.
 */
export function buildExecutiveSummary(
  input: ExecutiveSummaryInput,
): ExecutiveSummaryOutput {
  const kpis: KpiCard[] = [
    buildYtdRevenueCard(input.ytdRevenue),
    buildNoiCard(input.ytdNoiBeforeDepreciation),
    buildCapitalIncomeCard(input.ytdCapitalIncome),
    buildReserveCoverageCard(input.reserveCoverage),
    buildWorkingCapitalCard(input.workingCapital),
    buildArCard(input.arAging),
  ];
  const headline = buildExecutiveSummaryHeadline(input, kpis);
  const consideration = cascadeConsideration(kpis);

  // dataSource rollup — every input carries its own provenance.
  // The block reports `"live"` only when every input is
  // `accounting` or `operational`; any `demo` tag flips it to
  // `"demo"`. `derived` inputs would be unusual here (executive
  // summary inputs are aggregates from accounting/operational
  // services) so we use the shared mapping helper.
  const inputSources: MonthlyAccountingDataSource[] = [
    input.ytdRevenue.dataSource,
    input.ytdNoiBeforeDepreciation.dataSource,
    input.ytdCapitalIncome.dataSource,
    input.reserveCoverage.dataSource,
    input.workingCapital.dataSource,
    input.arAging.dataSource,
  ];
  if (input.fbSubsidy) inputSources.push(input.fbSubsidy.dataSource);
  const dataSource: ReportingDataSource = inputSources.every(
    (s) => toLegacyDataSource(s) === "live",
  )
    ? "live"
    : "demo";

  return { dataSource, kpis, headline, consideration };
}

// ---------------------------------------------------------------------------
// Demo input — preserves the existing seeded Silver Springs values
// ---------------------------------------------------------------------------

/**
 * Returns a believable `ExecutiveSummaryInput` tagged `dataSource:
 * "demo"` for every block. The dollar / ratio / percent values
 * preserve the historical Silver Springs cover-page numbers so the
 * package continues to render the same headline numbers as the
 * static literals it replaces — until Phase 1 wiring services
 * (`getGLAccountTotals`, `getBalanceSheet`, `getReserveCoverage`,
 * `getWorkingCapital`, `getCapitalIncomeYTD`) replace this builder
 * with prisma-backed values.
 */
export function buildDemoExecutiveSummaryInput(args: {
  period: ReportingPeriod;
  clubName: string;
}): ExecutiveSummaryInput {
  return {
    period: args.period,
    clubName: args.clubName,
    ytdRevenue: {
      actual: 14_620_000,
      comparator: 14_100_000,
      dataSource: "demo",
    },
    ytdNoiBeforeDepreciation: {
      actual: 3_180_000,
      comparator: 2_840_000,
      dataSource: "demo",
    },
    ytdCapitalIncome: {
      actual: 2_040_000,
      comparator: 1_950_000,
      dataSource: "demo",
    },
    reserveCoverage: {
      actual: 1.42,
      comparator: 1.25,
      dataSource: "demo",
    },
    workingCapital: {
      actual: 4_710_000,
      comparator: 3_500_000,
      dataSource: "demo",
    },
    arAging: {
      // For AR, `actual` = current %; `comparator` = over-90 %.
      actual: 0.784,
      comparator: 0.037,
      watchThreshold: 0.05,
      // AR is sourced from MemberAccount (subledger), not the GL —
      // tag as `operational` so a future package build that uses
      // the live AR aging service rolls up appropriately.
      dataSource: "operational",
    },
    fbSubsidy: {
      actual: 0.051,
      ceiling: 0.08,
      trend: "improving",
      dataSource: "demo",
    },
  };
}

/**
 * Convenience — build the full output directly from period + club
 * name using the demo input. Used as the default in
 * `monthly-package.ts` until Phase 1 wiring lands.
 */
export function buildDemoExecutiveSummary(args: {
  period: ReportingPeriod;
  clubName: string;
}): ExecutiveSummaryOutput {
  return buildExecutiveSummary(buildDemoExecutiveSummaryInput(args));
}

// =============================================================================
// Production entry point — DUAL-READ pattern
// =============================================================================
//
// Mirrors the SoFP + SoA migrations. The Executive Summary block (the
// cover-page At-a-Glance KPIs + reactive headline + board
// consideration) drives off live Reporting Ledger snapshots when
// they exist for the active club, falling back to the demo seed
// otherwise.
//
// LEDGER-DERIVED INPUTS (from Balance Sheet + Income Statement snapshots):
//   • ytdRevenue.actual                ← IS.totalOperatingRevenue
//   • ytdNoiBeforeDepreciation.actual  ← IS.noiBeforeDepreciation
//   • ytdCapitalIncome.actual          ← IS.totalCapitalIncome
//   • workingCapital.actual            ← BS  (current-asset sum − current-liability sum)
//
// AUXILIARY INPUTS (typed; awaiting their own ledger services):
//   • Budget comparators for all four monetary KPIs (await Budget importer)
//   • reserveCoverage.actual + comparator (await Reserve Study projection)
//   • workingCapital.comparator policy floor (await policy-table importer)
//   • arAging.* (await AR Aging projection)
//   • fbSubsidy.* (await F&B subledger aggregate)
//
// When any auxiliary input is missing, the corresponding KPI card
// renders a "Pending" comparator and tones neutral — the existing
// builder handles this gracefully (see PENDING_COMPARATOR_ROW above).

/**
 * Auxiliary inputs the Executive Summary needs from sources outside
 * the BS + IS snapshots. Each typed entry will move to its own
 * ledger projection in Phase 3.
 */
export type ExecutiveSummaryAuxiliaryInputs = {
  /** Budget comparators per KPI (null when not yet available). */
  budget: {
    ytdRevenue: number | null;
    ytdNoiBeforeDepreciation: number | null;
    ytdCapitalIncome: number | null;
    /** Working-capital policy floor (dollars). */
    workingCapitalFloor: number | null;
  };
  /** Reserve coverage — `actual` is the ratio (reserve balance ÷
   *  3-year average capital spend); `comparator` is the policy
   *  floor. Awaiting Reserve Study projection. */
  reserveCoverage: {
    actual: number | null;
    floor: number | null;
  };
  /** AR aging block. `actual` is the current-bucket share (0..1);
   *  `over90Pct` is the over-90 share; `watchThreshold` is the
   *  amber trigger. Awaiting AR Aging projection. */
  arAging: {
    actualCurrentPct: number | null;
    over90Pct: number | null;
    watchThreshold: number;
  };
  /** F&B subsidy — optional. Drives a sentence in the headline
   *  narrative. Awaiting F&B subledger aggregate. */
  fbSubsidy: FbSubsidyInput | null;
};

/**
 * Build an `ExecutiveSummaryInput` from BS + IS snapshots plus the
 * auxiliary inputs. Pure function; same inputs → same output.
 */
export function buildExecutiveSummaryInputFromSnapshots(args: {
  period: ReportingPeriod;
  clubName: string;
  ytdIncomeStatement: IncomeStatementSnapshot;
  balanceSheet: BalanceSheetSnapshot;
  auxiliaryInputs: ExecutiveSummaryAuxiliaryInputs;
}): ExecutiveSummaryInput {
  const { ytdIncomeStatement: is, balanceSheet: bs, auxiliaryInputs: aux } = args;

  // Working capital from BS lines (current-asset − current-liability).
  let currentAssets = 0;
  let currentLiabilities = 0;
  for (const l of bs.lines) {
    if (l.category === "current-asset") currentAssets += l.amount;
    else if (l.category === "current-liability") currentLiabilities += l.amount;
  }
  const workingCapital = currentAssets - currentLiabilities;

  // Provenance: tag accounting-derived inputs `accounting`, derived
  // (BS) as `derived`, others as `demo`/`operational` per their
  // upstream source.
  const accountingTag: MonthlyAccountingDataSource =
    is.dataSource === "demo" ? "demo" : "accounting";
  const derivedTag: MonthlyAccountingDataSource =
    bs.dataSource === "demo" ? "demo" : "derived";

  return {
    period: args.period,
    clubName: args.clubName,
    ytdRevenue: {
      actual: is.totalOperatingRevenue,
      comparator: aux.budget.ytdRevenue,
      dataSource: accountingTag,
    },
    ytdNoiBeforeDepreciation: {
      actual: is.noiBeforeDepreciation,
      comparator: aux.budget.ytdNoiBeforeDepreciation,
      dataSource: accountingTag,
    },
    ytdCapitalIncome: {
      actual: is.totalCapitalIncome,
      comparator: aux.budget.ytdCapitalIncome,
      dataSource: accountingTag,
    },
    reserveCoverage: {
      actual: aux.reserveCoverage.actual ?? 0,
      comparator: aux.reserveCoverage.floor,
      dataSource: aux.reserveCoverage.actual === null ? "demo" : "derived",
    },
    workingCapital: {
      actual: workingCapital,
      comparator: aux.budget.workingCapitalFloor,
      dataSource: derivedTag,
    },
    arAging: {
      actual: aux.arAging.actualCurrentPct ?? 0,
      comparator: aux.arAging.over90Pct ?? 0,
      watchThreshold: aux.arAging.watchThreshold,
      dataSource: aux.arAging.actualCurrentPct === null ? "demo" : "operational",
    },
    fbSubsidy: aux.fbSubsidy,
  };
}

/**
 * Production dual-read entry point. Resolves BS + YTD IS snapshots
 * from the ledger (self-healing projection from a TB when needed)
 * and builds the Executive Summary from them. Falls back to the
 * demo seed when no ledger data exists.
 */
export async function getExecutiveSummaryForClub(args: {
  clubId: string;
  clubName: string;
  period: ReportingPeriod;
  ledger: ReportingLedger & ReportingLedgerWriter;
  auxiliaryInputs: ExecutiveSummaryAuxiliaryInputs;
  demoFallback?: () => ExecutiveSummaryOutput;
}): Promise<ExecutiveSummaryOutput> {
  const snapshots = await resolveSnapshotsForExecutiveSummary({
    ledger: args.ledger,
    clubId: args.clubId,
    period: args.period,
  });

  if (snapshots) {
    return buildExecutiveSummary(
      buildExecutiveSummaryInputFromSnapshots({
        period: args.period,
        clubName: args.clubName,
        ytdIncomeStatement: snapshots.is,
        balanceSheet: snapshots.bs,
        auxiliaryInputs: args.auxiliaryInputs,
      }),
    );
  }

  if (args.demoFallback) return args.demoFallback();
  return buildDemoExecutiveSummary({
    period: args.period,
    clubName: args.clubName,
  });
}

// ---------------------------------------------------------------------------
// Snapshot resolver — self-healing (projects from TB on demand)
// ---------------------------------------------------------------------------

async function resolveSnapshotsForExecutiveSummary(args: {
  ledger: ReportingLedger & ReportingLedgerWriter;
  clubId: string;
  period: ReportingPeriod;
}): Promise<{ bs: BalanceSheetSnapshot; is: IncomeStatementSnapshot } | null> {
  const asOf = endOfDayUtc(args.period.periodEnd);
  const tb = await args.ledger.getTrialBalance(args.clubId, asOf);
  if (!tb) return null;

  // Founder rule 2026-07-01 v14.12 — direct snapshot preference.
  // v14.13 refinement — YTD Revenue means fiscal-year-start to
  // period-end, NOT month-start to period-end. Read the TB
  // snapshot's `periodStart` (populated by v14.11 synth to the
  // covering fiscal year start) so the IS query returns the full
  // YTD window even for mid-year periods.
  const directBs = await args.ledger.getBalanceSheet(args.clubId, asOf);
  const directIs = await args.ledger.getIncomeStatement(
    args.clubId,
    tb.periodStart,
    asOf,
  );
  if (directBs && directIs) {
    return { bs: directBs, is: directIs };
  }

  // BS projection — idempotent via payload hash; no-op write when TB
  // hasn't changed.
  const bsProj = new BalanceSheetProjection({
    ledger: args.ledger,
    writer: args.ledger,
  });
  const bsResult = await bsProj.getBalanceSheetSnapshot({
    clubId: args.clubId,
    asOf,
  });

  // IS projection — YTD mode.
  const isProj = new IncomeStatementProjection({
    ledger: args.ledger,
    writer: args.ledger,
  });
  const isResult = await isProj.getIncomeStatementSnapshot({
    clubId: args.clubId,
    periodStart: args.period.periodStart,
    periodEnd: asOf,
    fiscalYearLabel: tb.fiscalYearLabel,
    fiscalPeriodSequence: tb.fiscalPeriodSequence,
    mode: "ytd",
  });

  if (bsResult.status !== "succeeded" || isResult.status !== "succeeded") {
    return null;
  }
  return { bs: bsResult.snapshot, is: isResult.snapshot };
}

function endOfDayUtc(d: Date): Date {
  return new Date(
    Date.UTC(
      d.getUTCFullYear(),
      d.getUTCMonth(),
      d.getUTCDate(),
      23, 59, 59, 999,
    ),
  );
}

// =============================================================================
// Silver Springs auxiliary-input defaults
// =============================================================================
//
// Constant Silver Springs comparators that the dual-read passes on
// the LIVE branch until Budget / Reserve Study / AR Aging
// projections land. The values match what the seeded demo expressed
// so the rendered KPIs read with the same comparators regardless of
// which branch fires.

export const SILVER_SPRINGS_EXEC_SUMMARY_AUX: ExecutiveSummaryAuxiliaryInputs = {
  budget: {
    ytdRevenue: 14_100_000,
    ytdNoiBeforeDepreciation: 2_840_000,
    ytdCapitalIncome: 1_950_000,
    workingCapitalFloor: 3_500_000,
  },
  reserveCoverage: {
    actual: 1.42,
    floor: 1.25,
  },
  arAging: {
    actualCurrentPct: 0.784,
    over90Pct: 0.037,
    watchThreshold: 0.05,
  },
  fbSubsidy: {
    actual: 0.051,
    ceiling: 0.08,
    trend: "improving",
    dataSource: "demo",
  },
};
