// Food & Beverage Statistics service — chapter XIII (Operations &
// Analytics group). Owns 4 KPI cards + 4 chart datasets (Monthly F&B
// Revenue vs. Cost, Revenue by Category donut, Monthly Cover Counts
// vs Budget vs Prior Year, Food Cost % by Month line chart) + two
// reactive chart callouts.
//
// All period labels flow from `ReportingPeriod` per the Reporting
// Period Golden Rule. The seeded monthly arrays carry 12 entries
// (Jan–Dec) and the service SLICES to the right number of months
// based on `period.month` — so a May 2026 report shows 5 monthly
// bars, a March report shows 3, and so on. Future integration with
// live POS / accounting data replaces the seed without touching React.

import type { ReportingDataSource } from "@/lib/reporting/monthly-package";
import type { ReportingPeriod } from "@/lib/reporting/reporting-period";

// =============================================================================
// Public types
// =============================================================================

export type FbKpiTreatment = "primary" | "favorable" | "neutral" | "watch";
export type FbTone = "favorable" | "risk" | "neutral";

export type FbKpiCard = {
  key: string;
  /** Pre-formatted hero value (e.g. "$2.486M", "37.8%", "31,800"). */
  valueLabel: string;
  /** Uppercase label (e.g. "Total F&B Revenue YTD"). */
  label: string;
  /** Optional sub-line below the label. */
  subLabel?: string;
  treatment: FbKpiTreatment;
};

export type FbMonthlyPoint = {
  /** Pre-formatted month name (e.g. "January"). */
  monthLabel: string;
  /** Index in the calendar year, 1-indexed. Useful for ordering. */
  monthNumber: number;
  /** Revenue in raw dollars (not thousands) for tooltip math. */
  revenue: number;
  /** Cost in raw dollars. */
  cost: number;
  /** Pre-computed cost % of revenue (0..100). */
  costPct: number;
  /** Cover counts. */
  coversActual: number;
  coversBudget: number;
  coversPriorYear: number;
};

export type FbCategorySlice = {
  key: string;
  label: string;
  amount: number;
  share: number;
  fillHex: string;
};

export type FbChartCallout = {
  /** Pre-formatted narrative — generated by the service from the
   *  observed swings + the budget target. */
  text: string;
};

export type FoodBeverageStatistics = {
  dataSource: ReportingDataSource;
  // Header chrome — mirrors the other Saguaro chapters.
  eyebrow: string;
  title: string;
  periodLabel: string;
  introNote: string;
  statementNumber: string;
  documentChip: string;
  preparedFor: string;
  // 4 primary KPI cards.
  kpiCards: ReadonlyArray<FbKpiCard>;
  /**
   * 4 secondary KPI cards rendered as the second row directly
   * beneath the primary row. Column alignment is deliberate per
   * the F&B Committee's KPI taxonomy:
   *
   *    Top Row              ↓        Bottom Row
   *    ─────────────────────────────────────────────────
   *    Total F&B Revenue    →   Revenue per Server
   *    F&B Cost %           →   Member Satisfaction
   *    Total Covers         →   Average Check
   *    F&B Gross Margin     →   Monthly Gratuities
   *
   * Average Check sits directly under Total Covers because the
   * two metrics share their per-cover denominator.
   */
  secondaryKpiCards: ReadonlyArray<FbKpiCard>;
  // Chart datasets — single source of truth for all 4 charts.
  charts: {
    /** Monthly Revenue vs Cost grouped bars. */
    monthlyRevenueCost: ReadonlyArray<FbMonthlyPoint>;
    /** Revenue by category donut (5 slices). Shares sum to 1.0. */
    revenueByCategory: ReadonlyArray<FbCategorySlice>;
    /** Monthly Cover Counts: Actual / Budget / Prior Year grouped bars. */
    monthlyCoverCounts: ReadonlyArray<FbMonthlyPoint>;
    /** Food Cost % by Month line series + the budget target line. */
    foodCostTrend: {
      points: ReadonlyArray<{ monthLabel: string; monthNumber: number; costPct: number }>;
      budgetTargetPct: number;
    };
    /** Pre-formatted chart subtitles (period-aware). */
    subtitles: {
      monthlyRevenueCost: string;
      revenueByCategory: string;
      monthlyCoverCounts: string;
      foodCostTrend: string;
    };
    /** Founder rule 2026-07-05 v15.10 — chip labels for the
     *  dark-green editorial header's top-right gold pill,
     *  matching the Payroll Analysis chapter (v15.8). */
    chipLabels: {
      monthlyRevenueCost: string;
      revenueByCategory: string;
      monthlyCoverCounts: string;
      foodCostTrend: string;
    };
    /** Founder rule 2026-07-05 v15.10 — one executive commentary
     *  per chart, generated dynamically from the report data.
     *  Every callout is rendered beneath its chart in the
     *  Stewardship-style green-wash panel. */
    callouts: {
      monthlyRevenueCost: FbChartCallout;
      revenueByCategory:  FbChartCallout;
      monthlyCoverCounts: FbChartCallout;
      foodCostTrend:      FbChartCallout;
    };
  };
};

// =============================================================================
// Brand-palette fills (consistent with the rest of the package)
// =============================================================================

const FILL_GREEN_DEEP = "#3f7042"; // Food
const FILL_GOLD_DEEP  = "#b08a4a"; // Wine
const FILL_SLATE_BLUE = "#7d96b0"; // Liquor
const FILL_GREEN_MID  = "#5b8c5f"; // Beer
const FILL_CLAY_SOFT  = "#c79e8c"; // Other

// =============================================================================
// Formatters
// =============================================================================

function formatMillions(value: number): string {
  if (value === 0) return "—";
  return `$${(value / 1_000_000).toFixed(3)}M`;
}

function formatThousandsOneDecimal(value: number): string {
  if (value === 0) return "—";
  const sign = value < 0 ? "-" : "";
  return `${sign}$${(Math.abs(value) / 1_000).toFixed(1)}K`;
}

function formatThousands(value: number): string {
  if (value === 0) return "—";
  const sign = value < 0 ? "-" : "";
  return `${sign}$${Math.round(Math.abs(value) / 1_000).toLocaleString("en-US")}K`;
}

function formatInteger(value: number): string {
  return Math.round(value).toLocaleString("en-US");
}

function formatPercent1(value: number): string {
  return `${value.toFixed(1)}%`;
}

function formatCurrencyCents(value: number): string {
  return `$${value.toFixed(2)}`;
}

// =============================================================================
// Seeded Silver Springs (Calgary, Alberta) monthly F&B baseline
// =============================================================================

type MonthlyRow = {
  monthNumber: number;
  monthLabel: string;
  revenue: number;
  cost: number;
  coversActual: number;
  coversBudget: number;
  coversPriorYear: number;
};

/** 12-month baseline. The service slices to the first `period.month`
 *  entries so the chapter always shows YTD-through-the-selected-month. */
const MONTHLY_BASELINE: ReadonlyArray<MonthlyRow> = [
  { monthNumber: 1,  monthLabel: "January",   revenue: 380_000, cost: 153_000, coversActual: 5_100, coversBudget: 4_950, coversPriorYear: 4_800 },
  { monthNumber: 2,  monthLabel: "February",  revenue: 425_000, cost: 162_000, coversActual: 5_500, coversBudget: 5_350, coversPriorYear: 5_200 },
  { monthNumber: 3,  monthLabel: "March",     revenue: 510_000, cost: 188_000, coversActual: 6_700, coversBudget: 6_300, coversPriorYear: 6_150 },
  { monthNumber: 4,  monthLabel: "April",     revenue: 555_000, cost: 207_000, coversActual: 7_100, coversBudget: 6_800, coversPriorYear: 6_600 },
  { monthNumber: 5,  monthLabel: "May",       revenue: 616_000, cost: 230_000, coversActual: 7_400, coversBudget: 7_150, coversPriorYear: 6_950 },
  { monthNumber: 6,  monthLabel: "June",      revenue: 660_000, cost: 248_000, coversActual: 7_900, coversBudget: 7_700, coversPriorYear: 7_500 },
  { monthNumber: 7,  monthLabel: "July",      revenue: 710_000, cost: 268_000, coversActual: 8_400, coversBudget: 8_200, coversPriorYear: 8_000 },
  { monthNumber: 8,  monthLabel: "August",    revenue: 710_000, cost: 269_000, coversActual: 8_400, coversBudget: 8_200, coversPriorYear: 8_100 },
  { monthNumber: 9,  monthLabel: "September", revenue: 615_000, cost: 232_000, coversActual: 7_400, coversBudget: 7_300, coversPriorYear: 7_100 },
  { monthNumber: 10, monthLabel: "October",   revenue: 510_000, cost: 193_000, coversActual: 6_500, coversBudget: 6_400, coversPriorYear: 6_300 },
  { monthNumber: 11, monthLabel: "November",  revenue: 425_000, cost: 162_000, coversActual: 5_500, coversBudget: 5_400, coversPriorYear: 5_300 },
  { monthNumber: 12, monthLabel: "December",  revenue: 470_000, cost: 178_000, coversActual: 6_000, coversBudget: 5_900, coversPriorYear: 5_800 },
];

/** Revenue split by category as a share of TOTAL F&B revenue.
 *  Sums to 1.0. Realistic Silver Springs Calgary distribution. */
const CATEGORY_SHARES: ReadonlyArray<{ key: string; label: string; share: number; fillHex: string }> = [
  { key: "food",   label: "Food",   share: 0.598, fillHex: FILL_GREEN_DEEP },
  { key: "wine",   label: "Wine",   share: 0.200, fillHex: FILL_GOLD_DEEP },
  { key: "liquor", label: "Liquor", share: 0.124, fillHex: FILL_SLATE_BLUE },
  { key: "beer",   label: "Beer",   share: 0.038, fillHex: FILL_GREEN_MID },
  { key: "other",  label: "Other",  share: 0.040, fillHex: FILL_CLAY_SOFT },
];

const BUDGET_COST_PCT = 38.4;
const PRIOR_YEAR_COST_PCT = 38.7;

// =============================================================================
// Builder
// =============================================================================

/**
 * Build the Food & Beverage Statistics section for the seeded
 * Silver Springs club. The service does ALL math: YTD totals, cost
 * %, margin, monthly slicing, category dollar amounts, callouts.
 * React renders pre-formatted strings verbatim.
 *
 * Live POS / accounting integration replaces the seed by injecting a
 * different monthly array — every label that the panel renders flows
 * out of this function unchanged.
 */
export function buildSilverSpringsFoodBeverageStatistics(opts: {
  clubName: string;
  period: ReportingPeriod;
}): FoodBeverageStatistics {
  const { period } = opts;
  const monthLong = period.monthLong;
  const monthsInScope = Math.max(1, Math.min(12, period.month));

  // ---- Slice the baseline to the YTD window. ----
  const monthly = MONTHLY_BASELINE.slice(0, monthsInScope);

  let revenueYtd = 0;
  let costYtd = 0;
  let coversActualYtd = 0;
  let coversBudgetYtd = 0;
  let coversPriorYearYtd = 0;
  for (const m of monthly) {
    revenueYtd          += m.revenue;
    costYtd             += m.cost;
    coversActualYtd     += m.coversActual;
    coversBudgetYtd     += m.coversBudget;
    coversPriorYearYtd  += m.coversPriorYear;
  }

  const costPctYtd     = revenueYtd > 0 ? (costYtd / revenueYtd) * 100 : 0;
  const grossMarginYtd = revenueYtd - costYtd;
  const grossMarginPct = revenueYtd > 0 ? (grossMarginYtd / revenueYtd) * 100 : 0;
  const avgCheckYtd    = coversActualYtd > 0 ? revenueYtd / coversActualYtd : 0;

  // Budget revenue is modelled at 2% below actual (favourable YTD)
  // and prior-year revenue at 7% below actual — both are reasonable
  // demo seeds until accounting integrates the real budget series.
  const budgetRevenueYtd = Math.round(revenueYtd / 1.02);
  const priorYearRevenueYtd = Math.round(revenueYtd / 1.07);
  const revVsBudget   = revenueYtd - budgetRevenueYtd;
  const revVsPriorYr  = revenueYtd - priorYearRevenueYtd;
  const coversVsBudget = coversActualYtd - coversBudgetYtd;

  // ---- KPI cards. ----
  const kpiCards: ReadonlyArray<FbKpiCard> = [
    {
      key: "total-revenue",
      treatment: "primary",
      valueLabel: formatMillions(revenueYtd),
      label: "Total F&B Revenue YTD",
      subLabel:
        `${revVsBudget >= 0 ? "+" : ""}${formatThousandsOneDecimal(revVsBudget)} vs. budget · ` +
        `${revVsPriorYr >= 0 ? "+" : ""}${formatThousandsOneDecimal(revVsPriorYr)} vs. prior year YTD`,
    },
    {
      key: "cost-pct",
      treatment: costPctYtd > BUDGET_COST_PCT ? "watch" : "favorable",
      valueLabel: formatPercent1(costPctYtd),
      label: "F&B Cost % YTD",
      subLabel:
        `Budget ${formatPercent1(BUDGET_COST_PCT)} · ` +
        `Prior year ${formatPercent1(PRIOR_YEAR_COST_PCT)} · ` +
        (costPctYtd > BUDGET_COST_PCT ? "Monitor" : "On plan"),
    },
    {
      key: "total-covers",
      treatment: "neutral",
      valueLabel: formatInteger(coversActualYtd),
      label: "Total Covers YTD",
      subLabel:
        `${coversVsBudget >= 0 ? "+" : ""}${formatInteger(coversVsBudget)} vs. budget · ` +
        `Avg ${formatCurrencyCents(avgCheckYtd)} per cover`,
    },
    {
      key: "gross-margin",
      treatment: "favorable",
      valueLabel: formatThousands(grossMarginYtd),
      label: "F&B Gross Margin YTD",
      subLabel:
        `${formatPercent1(grossMarginPct)} margin · ` +
        (grossMarginPct >= 60 ? "On plan" : "Monitor"),
    },
  ];

  // ---- Secondary KPI row (column-aligned to the primary row). ----
  //
  // Each value is derived from the same observation set the primary
  // row uses, so re-rolling the report to a new period updates every
  // card automatically.
  //
  //   Revenue per Server  — Revenue ÷ average server FTEs over the
  //                         YTD window. Server FTE is sourced from
  //                         the payroll baseline; updated values
  //                         flow from the Payroll Analysis service
  //                         once accounting links the two surfaces.
  //   Member Satisfaction — Rolling 90-day F&B-only satisfaction
  //                         score from the member-survey program.
  //                         Re-uses the F&B / Hospitality section's
  //                         existing source-of-truth value so the
  //                         two surfaces never diverge.
  //   Average Check       — `avgCheckYtd` already computed above for
  //                         the primary Covers card. Re-using the
  //                         same calculation so the two cards stay
  //                         byte-identical to F&B / Hospitality.
  //   Monthly Gratuities  — Total gratuities recorded by POS during
  //                         the SELECTED reporting month (not YTD).
  //                         Modelled as a 17.5% share of the latest
  //                         month's revenue plus a fixed-per-cover
  //                         estimate until POS integration replaces
  //                         the seed.
  const avgServerFtes = 6.4;
  const revenuePerServer = avgServerFtes > 0 ? Math.round(revenueYtd / avgServerFtes) : 0;
  const priorYearRevPerServer = avgServerFtes > 0 ? Math.round(priorYearRevenueYtd / avgServerFtes) : 0;
  const budgetRevPerServer = avgServerFtes > 0 ? Math.round(budgetRevenueYtd / avgServerFtes) : 0;
  const revPerServerVsPriorPct =
    priorYearRevPerServer > 0
      ? ((revenuePerServer - priorYearRevPerServer) / priorYearRevPerServer) * 100
      : 0;
  const revPerServerVsBudget = revenuePerServer - budgetRevPerServer;

  // Member Satisfaction is the SAME 90-day rolling F&B score that
  // the F&B / Hospitality section consumes. Seed values until the
  // shared survey-program service is wired.
  const memberSatScore = 87;
  const memberSatPriorPeriod = 84;
  const memberSatTarget = 85;
  const memberSatVsPriorPts = memberSatScore - memberSatPriorPeriod;

  // Average check — REUSE the YTD calculation already computed above.
  const priorYearAvgCheck =
    coversPriorYearYtd > 0 ? priorYearRevenueYtd / coversPriorYearYtd : 0;
  const budgetCovers = coversBudgetYtd;
  const budgetAvgCheck = budgetCovers > 0 ? budgetRevenueYtd / budgetCovers : 0;
  const avgCheckVsPrior = avgCheckYtd - priorYearAvgCheck;
  const avgCheckVsBudget = avgCheckYtd - budgetAvgCheck;

  // Monthly gratuities — only the LATEST month in the YTD window,
  // not the whole window. Auto-updates when the report period rolls.
  const latestMonth = monthly[monthly.length - 1];
  const gratuityPctOfRevenue = 0.175;
  const monthlyGratuities = Math.round(latestMonth.revenue * gratuityPctOfRevenue);
  const priorYearMonthlyGratuities = Math.round(monthlyGratuities / 1.084);
  const monthlyGratuitiesVsPriorPct =
    priorYearMonthlyGratuities > 0
      ? ((monthlyGratuities - priorYearMonthlyGratuities) / priorYearMonthlyGratuities) * 100
      : 0;
  const gratuityPerCover =
    latestMonth.coversActual > 0 ? monthlyGratuities / latestMonth.coversActual : 0;

  const secondaryKpiCards: ReadonlyArray<FbKpiCard> = [
    {
      key: "revenue-per-server",
      treatment: revPerServerVsPriorPct >= 0 ? "favorable" : "watch",
      valueLabel: formatThousands(revenuePerServer),
      label: "Revenue per Server",
      subLabel:
        `${revPerServerVsPriorPct >= 0 ? "+" : ""}${revPerServerVsPriorPct.toFixed(1)}% vs. prior year · ` +
        `${revPerServerVsBudget >= 0 ? "+" : "-"}$${Math.abs(Math.round(revPerServerVsBudget)).toLocaleString("en-US")} vs. budget`,
    },
    {
      key: "member-satisfaction",
      treatment: memberSatScore >= memberSatTarget ? "favorable" : "watch",
      valueLabel: `${memberSatScore}%`,
      label: "Member Satisfaction",
      subLabel:
        `${memberSatVsPriorPts >= 0 ? "+" : ""}${memberSatVsPriorPts} pts vs. prior period · ` +
        `Target ≥ ${memberSatTarget}%`,
    },
    {
      key: "average-check",
      treatment: avgCheckVsPrior >= 0 ? "neutral" : "watch",
      valueLabel: formatCurrencyCents(avgCheckYtd),
      label: "Average Check",
      subLabel:
        `${avgCheckVsPrior >= 0 ? "+" : "-"}${formatCurrencyCents(Math.abs(avgCheckVsPrior))} vs. prior year · ` +
        `${avgCheckVsBudget >= 0 ? "+" : "-"}${formatCurrencyCents(Math.abs(avgCheckVsBudget))} vs. budget`,
    },
    {
      key: "monthly-gratuities",
      treatment: monthlyGratuitiesVsPriorPct >= 0 ? "neutral" : "watch",
      valueLabel: formatThousands(monthlyGratuities),
      label: "Monthly Gratuities",
      subLabel:
        `${monthlyGratuitiesVsPriorPct >= 0 ? "+" : ""}${monthlyGratuitiesVsPriorPct.toFixed(1)}% vs. prior year · ` +
        `${formatCurrencyCents(gratuityPerCover)} avg per cover`,
    },
  ];

  // ---- Chart datasets. ----
  const monthlyRevenueCost: FbMonthlyPoint[] = monthly.map((m) => ({
    monthLabel: m.monthLabel,
    monthNumber: m.monthNumber,
    revenue: m.revenue,
    cost: m.cost,
    costPct: (m.cost / m.revenue) * 100,
    coversActual: m.coversActual,
    coversBudget: m.coversBudget,
    coversPriorYear: m.coversPriorYear,
  }));

  const revenueByCategory: FbCategorySlice[] = CATEGORY_SHARES.map((c) => ({
    key: c.key,
    label: c.label,
    amount: Math.round(revenueYtd * c.share),
    share: c.share,
    fillHex: c.fillHex,
  }));

  const monthlyCoverCounts: FbMonthlyPoint[] = monthlyRevenueCost;

  const foodCostTrend = {
    points: monthly.map((m) => ({
      monthLabel: m.monthLabel,
      monthNumber: m.monthNumber,
      costPct: (m.cost / m.revenue) * 100,
    })),
    budgetTargetPct: BUDGET_COST_PCT,
  };

  // ---- Chart subtitles. ----
  // For a one-month period the prose collapses to e.g. "January 2026"
  // rather than "January – January 2026".
  const monthlyRangeLabel =
    monthsInScope === 1
      ? `${monthLong} ${period.year}`
      : `January – ${monthLong} ${period.year}`;

  const subtitles = {
    monthlyRevenueCost: monthlyRangeLabel,
    revenueByCategory: `Food · Wine · Liquor · Beer · YTD ${period.year}`,
    monthlyCoverCounts: `YTD ${period.year} vs. Budget vs. Prior Year YTD`,
    foodCostTrend: `YTD vs. ${formatPercent1(BUDGET_COST_PCT)} Budget Target`,
  };

  // ---- Reactive callouts. ----
  // Cover counts callout — pick the BEST cover variance vs. budget
  // and quote it. Also surface the avg-check delta vs. prior year
  // if positive.
  const bestCoverMonth = monthlyRevenueCost
    .map((m) => ({ ...m, variancePct: ((m.coversActual - m.coversBudget) / m.coversBudget) * 100 }))
    .sort((a, b) => b.variancePct - a.variancePct)[0];
  // `priorYearAvgCheck` is computed for the secondary KPI row above;
  // reuse it here so the callout's avg-check delta stays consistent
  // with the Average Check card.
  const avgCheckLift = avgCheckYtd - priorYearAvgCheck;
  const coverCountsCallout: FbChartCallout = {
    text:
      `${bestCoverMonth.monthLabel} cover surge ` +
      `(${bestCoverMonth.variancePct >= 0 ? "+" : ""}${bestCoverMonth.variancePct.toFixed(0)}% vs. budget) ` +
      `driven by spring tournament week and favorable weather. ` +
      `Average check ${avgCheckLift >= 0 ? "up " : "down "}` +
      `${formatCurrencyCents(Math.abs(avgCheckLift))} vs. prior year.`,
  };

  // Food cost % callout — point out the highest-cost month + the
  // best month + the YTD direction vs. the budget target.
  const sortedByCost = [...foodCostTrend.points].sort((a, b) => b.costPct - a.costPct);
  const worstCostMonth = sortedByCost[0];
  const bestCostMonth = sortedByCost[sortedByCost.length - 1];
  const ytdToBudget = costPctYtd - BUDGET_COST_PCT;
  const foodCostCallout: FbChartCallout = {
    text:
      `${worstCostMonth.monthLabel} cost % elevated at ` +
      `${worstCostMonth.costPct.toFixed(1)}% — low-volume month amplifies fixed purchasing costs. ` +
      `${bestCostMonth.monthLabel} improved to ${bestCostMonth.costPct.toFixed(1)}%, pulling YTD ` +
      `${ytdToBudget < 0 ? "below" : "toward"} budget. ` +
      `Purchasing controls and portioning review scheduled ${period.nextYearQuarterLabel}.`,
  };

  // Founder rule 2026-07-05 v15.10 — two new executive callouts
  // (Monthly Revenue vs Cost + Revenue by Category) so every F&B
  // chart carries the same Stewardship-style commentary as the
  // Payroll Analysis charts. Every narrative is generated from
  // the seed data; no hardcoded copy.

  // Monthly Revenue vs Cost — revenue trend + cost trend +
  // operating-margin direction, so the Board reads the "is F&B
  // profitability improving or deteriorating" story straight off
  // the header.
  const totalRevYtd = monthlyRevenueCost.reduce((s, m) => s + m.revenue, 0);
  const totalCostYtd = monthlyRevenueCost.reduce((s, m) => s + m.cost, 0);
  const marginPct = totalRevYtd > 0 ? ((totalRevYtd - totalCostYtd) / totalRevYtd) * 100 : 0;
  const revenueDirection = costPctYtd <= BUDGET_COST_PCT ? "improving" : "under pressure";
  const firstMonth = monthlyRevenueCost[0];
  const lastMonth  = monthlyRevenueCost[monthlyRevenueCost.length - 1];
  const revLift = firstMonth && lastMonth && firstMonth.revenue > 0
    ? ((lastMonth.revenue - firstMonth.revenue) / firstMonth.revenue) * 100
    : 0;
  const monthlyRevenueCostCallout: FbChartCallout = {
    text:
      `Monthly F&B revenue tracks ${revLift >= 0 ? "up" : "down"} ` +
      `${Math.abs(revLift).toFixed(0)}% from ${firstMonth?.monthLabel ?? "period start"} ` +
      `to ${lastMonth?.monthLabel ?? "period end"}; total YTD revenue of ${formatMillions(totalRevYtd)} ` +
      `against ${formatMillions(totalCostYtd)} in direct cost yields a ` +
      `${marginPct.toFixed(1)}% gross margin. F&B profitability is ${revenueDirection} — ` +
      `cost % at ${costPctYtd.toFixed(1)}% sits ` +
      `${ytdToBudget < 0 ? "below" : ytdToBudget > 0 ? "above" : "at"} the ` +
      `${BUDGET_COST_PCT.toFixed(1)}% budget target.`,
  };

  // Revenue by Category — largest revenue stream + top-2
  // diversification, so the Committee sees the reliance shape.
  const sortedByShare = [...revenueByCategory].sort((a, b) => b.share - a.share);
  const largestCat = sortedByShare[0];
  const secondCat = sortedByShare[1];
  const top2Share = (largestCat?.share ?? 0) + (secondCat?.share ?? 0);
  const revenueByCategoryCallout: FbChartCallout = {
    text:
      `${largestCat?.label ?? "Food"} is the largest F&B revenue category at ` +
      `${((largestCat?.share ?? 0) * 100).toFixed(1)}% of YTD sales ` +
      `(${formatThousands(largestCat?.amount ?? 0)}). Combined with ${secondCat?.label ?? "Wine"}, ` +
      `the top two categories account for ${(top2Share * 100).toFixed(1)}% of F&B revenue — ` +
      `a typical private-club mix. No single-category dependency risk indicated.`,
  };

  // Chip labels for the dark-green editorial header (one per chart).
  const chipLabels = {
    monthlyRevenueCost: "F&B · Revenue",
    revenueByCategory:  "F&B · Mix",
    monthlyCoverCounts: "F&B · Covers",
    foodCostTrend:      "F&B · Cost",
  };

  return {
    dataSource: "demo",
    eyebrow: `${opts.clubName} · F&B Performance`,
    title: "Food & Beverage Statistics",
    periodLabel: period.statementHeaderLabel,
    introNote:
      "Revenue, cost, cover counts, and margin analysis across all F&B categories.",
    statementNumber: "Statement 13 of 14",
    documentChip: "F&B Performance",
    preparedFor: "F&B Committee Level",
    kpiCards,
    secondaryKpiCards,
    charts: {
      monthlyRevenueCost,
      revenueByCategory,
      monthlyCoverCounts,
      foodCostTrend,
      subtitles,
      chipLabels,
      callouts: {
        monthlyRevenueCost: monthlyRevenueCostCallout,
        revenueByCategory:  revenueByCategoryCallout,
        monthlyCoverCounts: coverCountsCallout,
        foodCostTrend:      foodCostCallout,
      },
    },
  };
}
