/**
 * WEB-1D · Shared auth-surface hero photograph.
 *
 * Two entry points:
 *  - HeroPicture   → admin login (cliffside clubhouse, echoes the marketing hero)
 *  - PortalPicture → employee login (dark tree-framed distant flag — quieter,
 *                    more atmospheric, no institutional silhouette)
 *
 * Both use the WEB-1C.1 responsive pipeline (AVIF → WebP → JPEG with srcSet
 * and `sizes`). Assets are pre-generated by
 * scripts/web1c1-generate-responsive.mjs and served from /public/marketing/
 * photography/responsive/.
 */

interface Props {
  className?: string;
  alt?: string;
}

const CLIFF_WIDTHS = [480, 768, 1024, 1440, 1920, 2560];
const TREE_WIDTHS  = [480, 768, 1024, 1440, 1920];

function pictureFor(base: string, widths: number[], alt: string, className?: string) {
  const jpeg = widths.map((w) => `/marketing/photography/responsive/${base}-${w}.jpg ${w}w`).join(", ");
  const webp = widths.map((w) => `/marketing/photography/responsive/${base}-${w}.webp ${w}w`).join(", ");
  const avif = widths.map((w) => `/marketing/photography/responsive/${base}-${w}.avif ${w}w`).join(", ");
  const fallback = `/marketing/photography/responsive/${base}-${widths[widths.length - 1]}.jpg`;
  const sizes = "(max-width: 900px) 100vw, 55vw";
  return (
    <picture className={className}>
      <source type="image/avif" srcSet={avif} sizes={sizes} />
      <source type="image/webp" srcSet={webp} sizes={sizes} />
      <source type="image/jpeg" srcSet={jpeg} sizes={sizes} />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={fallback} alt={alt} loading="eager" fetchPriority="high" decoding="async" />
    </picture>
  );
}

export function HeroPicture({ className, alt }: Props = {}) {
  return pictureFor(
    "spectre-clubhouse",
    CLIFF_WIDTHS,
    alt ?? "Coastal clubhouse on a cliff above a golf green and Pacific Ocean",
    className,
  );
}

export function PortalPicture({ className, alt }: Props = {}) {
  return pictureFor(
    "spectre-hero-club-flag",
    TREE_WIDTHS,
    alt ?? "Golf flag framed by trees on a shaded course",
    className,
  );
}
