/**
 * WEB-1D.1 · Shared auth-surface hero photograph. Three-image hierarchy:
 *  - Marketing homepage → cliffside clubhouse (see PlatformHomeFramer.Hero)
 *  - Admin login  → HeroPicture   = red 18 flag
 *  - Employee    → PortalPicture = dark tree-framed distant flag
 *
 * Each surface gets its own visual moment; no photograph repeats across
 * marketing + admin surfaces. Same responsive pipeline in all cases:
 * AVIF → WebP → JPEG with srcSet + sizes, pre-generated by
 * scripts/web1c1-generate-responsive.mjs.
 */

interface Props {
  className?: string;
  alt?: string;
}

const BALL_WIDTHS = [480, 768, 1024, 1440, 1920];
const TREE_WIDTHS = [480, 768, 1024, 1440, 1920];

function pictureFor(base: string, widths: number[], alt: string, className?: string) {
  const jpeg = widths.map((w) => `/marketing/photography/responsive/${base}-${w}.jpg ${w}w`).join(", ");
  const webp = widths.map((w) => `/marketing/photography/responsive/${base}-${w}.webp ${w}w`).join(", ");
  const avif = widths.map((w) => `/marketing/photography/responsive/${base}-${w}.avif ${w}w`).join(", ");
  const fallback = `/marketing/photography/responsive/${base}-${widths[widths.length - 1]}.jpg`;
  const sizes = "(max-width: 900px) 100vw, 55vw";
  return (
    <picture className={className}>
      <source type="image/avif" srcSet={avif} sizes={sizes} />
      <source type="image/webp" srcSet={webp} sizes={sizes} />
      <source type="image/jpeg" srcSet={jpeg} sizes={sizes} />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={fallback} alt={alt} loading="eager" fetchPriority="high" decoding="async" />
    </picture>
  );
}

export function HeroPicture({ className, alt }: Props = {}) {
  return pictureFor(
    "spectre-admin-golf-ball",
    BALL_WIDTHS,
    alt ?? "Titleist golf ball on a red tee against a black field",
    className,
  );
}

export function PortalPicture({ className, alt }: Props = {}) {
  return pictureFor(
    "spectre-hero-club-flag",
    TREE_WIDTHS,
    alt ?? "Golf flag framed by trees on a shaded course",
    className,
  );
}
